# Site settings
title: Jennifer Sobeck
email: joneillsobeck@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "jsobeck.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oneillleo
github_username:  jsobeck

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
