# Site settings
title: Jennifer Sobeck
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jsobeck.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: joneillsobeck@gmail.com
twitter_username: oneillleo
github_username:  jsobeck
linkedin_username: jsobeck
ORCID: 0000-0002-4989-0353

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Exclude these files from production website 
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - README.md
